# Generated by Django 5.0.7 on 2024-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCIDENT_NO', models.CharField(max_length=20)),
                ('LGA_NAME', models.CharField(max_length=20)),
                ('LATITUDE', models.DecimalField(decimal_places=16, max_digits=22)),
                ('LONGITUDE', models.DecimalField(decimal_places=16, max_digits=22)),
                ('POSTCODE_CRASH', models.CharField(max_length=5)),
            ],
        ),
    ]
